### PR TITLE
MyAlerts 2.0 Integration

### PR DESCRIPTION
**Pull request by jnschrag**
Gives users the option to be notified via an alert when they are awarded feedback by other members.

### CODE REVIEW

**Comment by dragonexpert** [comment]
Do you have a working demo of this so I can test it?

**Comment by jnschrag** [comment]
Not a public one. I've been testing it locally. I can take a screencast of it later if that works?

**Comment by dragonexpert** [comment]
That will work for me.

**Comment by jnschrag** [comment]
Here is a screencast of the MyAlerts integration. Let me know if you need to see anything else.
http://quick.as/8WLZC627L

**Comment by dragonexpert** [comment]
Thanks.  Approved.

**Pull request merged**
