### PR TITLE
Updated feedback link from thread & URL parser

### PR DESCRIPTION
**Pull request by jnschrag**
- Changed give thread feedback to thread author link to a postbit button for all participants in a thread.
- When giving feedback directly from the thread, it will autofill the full URL instead of just the thread ID.

screen shot 2015-07-14 at 3 32 55 pm
screen shot 2015-07-14 at 3 32 37 pm

### CODE REVIEW

**Comment by jnschrag** [comment]
Updated PR with report center integration. Instead of sending global moderators an email, reporting a feedback will add it to the report center (or sent via email or PM depending on the board's settings).

screen shot 2015-07-16 at 2 59 44 pm
screen shot 2015-07-16 at 3 00 02 pm
screen shot 2015-07-16 at 3 00 14 pm
screen shot 2015-07-16 at 3 00 45 pm

**Comment by dragonexpert** [comment]
WHen I looked through the first two commits, I noticed you used $mybb->user['isbannedgroup']; this shouldbe $mybb->usergroup['isbannedgroup'].  Haven't checked the other two yet.

**Comment by dragonexpert** [comment]
I'm merging this now so I can work on some issues without creating a merge conflict.

**Comment by jnschrag** [comment]
Sounds good. I found a few other small issues and will submit them in a new PR sometime this week.

**Pull request merged**
